channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - pytest
    - pytest-coverage
    - pytest-xdist
  - h5py
  - mpi4py
  - matplotlib
  - Pillow
  - numpy
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - tensorflow
  - Keras
  - joblib
  - time
  - pyyaml
  - jupyterlab
